export enum QUERY_KEYS {
    membership = 'membership',
    isLoggedIn = 'isLoggedIn',
    jwtPayload = 'jwtPayload',
    ad = 'ad',
    posts = 'posts',
    bio = 'bio',
    post = 'post',
    all_users = 'users-all',
    filtered_users = 'users-filtered',
    roles = 'roles',
    my_timeline = 'my-timeline',
    likes = 'likes',
    follow_status = 'follow-status',
    followers = 'followers',
    payment_data = 'payment-data',
    ad_manager = 'ad-manager',
    ad_list = 'ad-list',
    deployment_health = 'deployment-health',
}
