apiVersion: skaffold/v2beta18
kind: Config
build:
  artifacts:
    # context is the directory with the Dockerfile for that image
    - image: unguard-frontend
      context: frontend
    - image: unguard-microblog-service # adapt jib patch index below if you move this item
      context: microblog-service
    - image: unguard-proxy-service
      context: proxy-service
    - image: unguard-user-simulator
      context: user-simulator
    - image: unguard-user-auth-service
      context: user-auth-service
    - image: unguard-ad-service
      context: ad-service
  local:
    # only the docker CLI respects a manually logged-in daemon
    useDockerCLI: true
    # BuildKit provides an improvement on performance
    useBuildkit: true
deploy:
  kustomize:
    paths:
      - ./k8s-manifests/base
  helm:
    releases:
      - name: unguard-mariadb
        remoteChart: mariadb
        repo: https://charts.bitnami.com/bitnami
        namespace: unguard
        createNamespace: true
        wait: true # TODO: might be removed once we have readiness probes (CASP-8983)
        overrides:
          primary:
            persistence:
              enabled: false
profiles:
  - name: aws
    activation:
      - kubeContext: "arn:aws:eks:*"
    build:
    deploy:
      kustomize:
        paths:
          - ./k8s-manifests/aws
  - name: gcp
    deploy:
      kustomize:
        paths:
          - ./k8s-manifests/gcp
  - name: localdev-minikube
    deploy:
      kustomize:
        paths:
          - ./k8s-manifests/localdev/minikube
  - name: localdev-kind
    deploy:
      kustomize:
        paths:
          - ./k8s-manifests/localdev/kind
  - name: falco
    patches:
      - op: add
        path: /deploy/helm/releases/-
        value:
          name: falco
          remoteChart: falco
          repo: https://falcosecurity.github.io/charts
          setValues:
            falcosidekick.enabled: true
            falcosidekick.webui.enabled: true
  - name: jaeger-dev
    patches:
      - op: add
        path: /deploy/kustomize/paths/-
        value: ./k8s-manifests/jaeger
      - op: add
        path: /deploy/helm/releases/-
        value:
          name: jaeger-operator
          remoteChart: jaeger-operator
          repo: https://jaegertracing.github.io/helm-charts
          namespace: unguard
          createNamespace: true
  - name: jaeger
    patches:
      - op: add
        path: /deploy/helm/releases/-
        value:
          name: jaeger
          remoteChart: jaeger
          repo: https://jaegertracing.github.io/helm-charts
          namespace: unguard
          createNamespace: true
          overrides:
            provisionDataStore:
              cassandra: false
              elasticsearch: true
            storage:
              type: elasticsearch
            elasticsearch:
              antiAffinity: soft
              replicas: 1
              minimumMasterNodes: 1
            esIndexCleaner:
              enabled: true
              tag: 1.22
              schedule: "55 23 * * *"
              numberOfDays: 7
  - name: jib
    patches:
      - op: add
        path: /build/artifacts/1/jib
        value: {}
