apiVersion: skaffold/v2beta14
kind: Config
build:
  artifacts:
    # image tags are relative; to specify an image repo (e.g. GCR), you
    # must provide a "default repo" using one of the methods described
    # here: https://skaffold.dev/docs/concepts/#image-repository-handling
    - image: vogelgrippe-frontend
      context: frontend
    - image: vogelgrippe-microblog-service
      context: microblog-service
      jib: { }
    - image: vogelgrippe-proxy-service
      context: proxy-service
    - image: vogelgrippe-loadgenerator
      context: loadgenerator
    - image: vogelgrippe-user-auth-service
      context: user-auth-service
  tagPolicy:
    gitCommit: { }
  local:
    useDockerCLI: true
    useBuildkit: true
deploy:
  helm:
    releases:
      - name: mariadb-release
        remoteChart: bitnami/mariadb
        namespace: vogelgrippe
        createNamespace: true
        wait: true
        overrides:
          primary:
            persistence:
              enabled: false
  kubectl:
    manifests:
      - ./k8s-manifests/base/frontend.yaml
      - ./k8s-manifests/base/loadgenerator.yaml
      - ./k8s-manifests/base/microblog-service.yaml
      - ./k8s-manifests/base/proxy-service.yaml
      - ./k8s-manifests/base/redis.yaml
      - ./k8s-manifests/base/user-auth-service.yaml
    flags:
      global:
        [ "--namespace=vogelgrippe" ]
  kustomize:
    paths:
    - "./k8s-manifests/base"
    defaultNamespace: "vogelgrippe"
profiles:
  - name: aws
    activation:
      - kubeContext: "arn:aws:eks:*"
    build:
      tagPolicy:
        sha256: { } # uses the latest tag
    patches:
      - op: remove
        path: /deploy/kubectl/manifests/0
      - op: replace
        path: /deploy/kustomize/paths/0
        value: "./k8s-manifests/aws"
      - op: add
        path: /deploy/kubectl/manifests/-
        value: ./k8s-manifests/aws/ingress.aws.yaml
  - name: falco
    patches:
      - op: add
        path: /deploy/helm/releases/-
        value:
          name: falco
          remoteChart: falcosecurity/falco
          setValues:
            falcosidekick.enabled: true
            falcosidekick.webui.enabled: true
  - name: jaeger
    patches:
      - op: add
        path: /deploy/helm/releases/-
        value:
          name: jaeger-operator
          remoteChart: jaegertracing/jaeger-operator
          namespace: vogelgrippe
          createNamespace: true
      - op: add
        path: /deploy/kubectl/manifests/-
        value: ./k8s-manifests/extra/jaeger.yaml