apiVersion: skaffold/v2beta18
kind: Config
build:
  artifacts:
    # context is the directory with the Dockerfile for that image
    - image: vogelgrippe-frontend
      context: frontend
    - image: vogelgrippe-microblog-service
      context: microblog-service
      jib: {}
    - image: vogelgrippe-proxy-service
      context: proxy-service
    - image: vogelgrippe-loadgenerator
      context: loadgenerator
    - image: vogelgrippe-user-auth-service
      context: user-auth-service
  tagPolicy:
    # use the commit hash
    gitCommit: {}
  local:
    # only the docker CLI respects a manually logged-in daemon
    useDockerCLI: true
    # buildkit provides cleaner output
    useBuildkit: true
deploy:
  kustomize:
    paths:
      - ./k8s-manifests/base
  helm:
    releases:
      - name: mariadb-release
        remoteChart: bitnami/mariadb
        namespace: vogelgrippe
        createNamespace: true
        wait: true # CASP-8983: might be removed once we have readiness probes
        overrides:
          primary:
            persistence:
              enabled: false
profiles:
  - name: aws
    activation:
      - kubeContext: "arn:aws:eks:*"
    build:
      tagPolicy:
        sha256: {} # uses the :latest tag
    deploy:
      kustomize:
        paths:
          - ./k8s-manifests/aws
  - name: falco
    patches:
      - op: add
        path: /deploy/helm/releases/-
        value:
          name: falco
          remoteChart: falcosecurity/falco
          setValues:
            falcosidekick.enabled: true
            falcosidekick.webui.enabled: true
  - name: jaeger
    patches:
      - op: add
        path: /deploy/kustomize/paths/-
        value: ./k8s-manifests/jaeger
      - op: add
        path: /deploy/helm/releases/-
        value:
          name: jaeger-operator
          remoteChart: jaegertracing/jaeger-operator
          namespace: vogelgrippe
          createNamespace: true
