apiVersion: skaffold/v2beta18
kind: Config
build:
  artifacts:
    # context is the directory with the Dockerfile for that image
    - image: unguard-frontend
      context: frontend
    - image: unguard-microblog-service
      context: microblog-service
      jib: {}
    - image: unguard-proxy-service
      context: proxy-service
    - image: unguard-load-generator
      context: load-generator
    - image: unguard-user-auth-service
      context: user-auth-service
    - image: unguard-ad-service
      context: ad-service
  tagPolicy:
    # use the commit hash
    gitCommit: {}
  local:
    # only the docker CLI respects a manually logged-in daemon
    useDockerCLI: true
    # BuildKit provides an improvement on performance
    useBuildkit: true
deploy:
  kustomize:
    paths:
      - ./k8s-manifests/base
    defaultNamespace: unguard
  helm:
    releases:
      - name: unguard-mariadb
        remoteChart: bitnami/mariadb
        namespace: unguard
        createNamespace: true
        wait: true # TODO: might be removed once we have readiness probes (CASP-8983)
        overrides:
          primary:
            persistence:
              enabled: false
profiles:
  - name: aws
    activation:
      - kubeContext: "arn:aws:eks:*"
    build:
      tagPolicy:
        sha256: {} # uses the :latest tag
    deploy:
      kustomize:
        paths:
          - ./k8s-manifests/aws
        defaultNamespace: unguard
  - name: falco
    patches:
      - op: add
        path: /deploy/helm/releases/-
        value:
          name: falco
          remoteChart: falcosecurity/falco
          setValues:
            falcosidekick.enabled: true
            falcosidekick.webui.enabled: true
  - name: jaeger
    patches:
      - op: add
        path: /deploy/kustomize/paths/-
        value: ./k8s-manifests/jaeger
      - op: add
        path: /deploy/helm/releases/-
        value:
          name: jaeger-operator
          remoteChart: jaegertracing/jaeger-operator
          namespace: unguard
          createNamespace: true
