{{- /*
Copyright 2023 Dynatrace LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}
apiVersion: v1
kind: Service
metadata:
  name: unguard-{{.Values.adService.name}}
  labels:
    app.kubernetes.io/name: {{.Values.adService.name}}
    app.kubernetes.io/part-of: unguard
spec:
  type: {{ .Values.adService.service.type }}
  selector:
    app.kubernetes.io/name: {{.Values.adService.name}}
    app.kubernetes.io/part-of: unguard
  ports:
 {{- .Values.adService.service.ports | toYaml | nindent 4 }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unguard-{{.Values.adService.name}}
  labels:
    app.kubernetes.io/name: {{.Values.adService.name}}
    app.kubernetes.io/part-of: unguard
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{.Values.adService.name}}
      app.kubernetes.io/part-of: unguard
  strategy:
    type: {{.Values.adService.deployment.strategy.type}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{.Values.adService.name}}
        app.kubernetes.io/part-of: unguard
    spec:
      containers:
        - name: {{.Values.adService.name}}
          image: {{.Values.adService.deployment.container.image.repository}}:{{.Values.adService.deployment.container.image.tag}}
          imagePullPolicy: {{.Values.adService.deployment.container.image.pullPolicy}}
          ports:
            - containerPort: {{.Values.adService.deployment.container.ports.containerPort}}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ quote .Values.adService.deployment.container.env.ASPNETCORE_ENVIRONMENT }}
            - name: SERVER_PORT
              value: {{ quote .Values.adService.deployment.container.env.SERVER_PORT }}
            - name: API_PATH
              value: {{ quote .Values.adService.deployment.container.env.API_PATH }}
            - name: USER_AUTH_SERVICE_ADDRESS
              value: {{ quote .Values.adService.deployment.container.env.USER_AUTH_SERVICE_ADDRESS }}
            - name: JAEGER_SERVICE_NAME
              value: {{quote (printf "unguard-%s" .Values.adService.name) }}
            - name: JAEGER_AGENT_HOST
              value: {{ quote (printf "%s-%s" .Values.jaeger.name .Values.adService.deployment.container.env.JAEGER_AGENT_HOST) }}
            - name: JAEGER_SAMPLER_TYPE
              value: {{ quote .Values.adService.deployment.container.env.JAEGER_SAMPLER_TYPE }}
            - name: JAEGER_SAMPLER_PARAM
              value: {{ quote .Values.adService.deployment.container.env.JAEGER_SAMPLER_PARAM }}
            - name: JAEGER_DISABLED
              value: {{ quote .Values.adService.deployment.container.env.JAEGER_DISABLED }}
