apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unguard-ingress
spec:
  rules:
    - host: unguard.kube
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: unguard-frontend
                port:
                  number: 80
