apiVersion: networking.k8s.io/v1beta1 # kubernetes version <= v1.21
kind: Ingress
metadata:
  name: unguard-ingress
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: unguard
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: "ground-zero-unguard"
    alb.ingress.kubernetes.io/scheme: internet-facing
    kubernetes.io/ingress.class: alb
spec:
  rules:
    - http:
        paths:
          - path: /ui
            backend:
              serviceName: unguard-frontend
              servicePort: 80
          - path: /ad-service
            backend:
              serviceName: unguard-ad-service
              servicePort: 80
