apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patchesStrategicMerge:
  - |-
    apiVersion: v1
    kind: Service
    metadata:
      name: unguard-frontend
    spec:
      type: NodePort
