apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: unguard
resources:
  - ../base
  - ingress-v1.yaml
patchesStrategicMerge:
  - |-
    apiVersion: v1
    kind: Service
    metadata:
      name: unguard-frontend
    spec:
      type: NodePort
  - |-
    apiVersion: v1
    kind: Service
    metadata:
      name: unguard-ad-service
    spec:
      type: NodePort
