apiVersion: v1
kind: Service
metadata:
  name: vogelgrippe-frontend
spec:
  ports:
    - targetPort: 3000
      port: 80
  type: ClusterIP
  selector:
    app: vogelgrippe-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vogelgrippe-frontend
spec:
  selector:
    matchLabels:
      app: vogelgrippe-frontend
  template:
    metadata:
      labels:
        app: vogelgrippe-frontend
    spec:
      containers:
        - name: frontend
          image: vogelgrippe-frontend
          ports:
            - containerPort: 3000
          env:
            - name: JAEGER_SERVICE_NAME
              value: "vogelgrippe-frontend"
            - name: JAEGER_AGENT_HOST
              value: "jaeger-agent" # change depending on your jaeger deployment
            - name: JAEGER_SAMPLER_TYPE
              value: "const"
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
            - name: MICROBLOG_SERVICE_ADDRESS
              value: "vogelgrippe-microblog-service"
            - name: PROXY_SERVICE_ADDRESS
              value: "vogelgrippe-proxy-service"
            - name: USER_AUTH_SERVICE_ADDRESS
              value: "vogelgrippe-user-auth-service"
            - name: AD_SERVICE_ADDRESS
              value: "localhost:8082" # TODO: change back to vogelgrippe-ad-service when issue with ingress is resolved (https://dev-jira.dynatrace.org/browse/CASP-10192)
