apiVersion: apps/v1
kind: Deployment
metadata:
  name: vogelgrippe-loadgenerator
spec:
  selector:
    matchLabels:
      app: loadgenerator
  replicas: 1
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      containers:
        - name: main
          image: vogelgrippe-loadgenerator
          env:
            - name: FRONTEND_ADDR
              value: "vogelgrippe-frontend:80"
            - name: USERS
              value: "5"
          resources:
            requests:
              cpu: 300m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi