apiVersion: v1
kind: Service
metadata:
  name: vogelgrippe-microblog-service
spec:
  ports:
    - targetPort: 8080
      port: 80
  type: ClusterIP
  selector:
    app: vogelgrippe-microblog-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vogelgrippe-microblog-service
spec:
  selector:
    matchLabels:
      app: vogelgrippe-microblog-service
  template:
    metadata:
      labels:
        app: vogelgrippe-microblog-service
    spec:
      containers:
        - name: microblog-service
          image: vogelgrippe-microblog-service
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: JAEGER_SERVICE_NAME
              value: "vogelgrippe-microblog-service"
            - name: JAEGER_AGENT_HOST
              value: "jaeger-agent" # change depending on your jaeger deployment
            - name: JAEGER_ENDPOINT
              value: "http://jaeger-collector:14268/api/traces"
            - name: JAEGER_SAMPLER_TYPE
              value: "const"
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
            - name: REDIS_SERVICE_ADDRESS
              value: "vogelgrippe-redis"
            - name: USER_AUTH_SERVICE_ADDRESS
              value: "vogelgrippe-user-auth-service"