apiVersion: apps/v1
kind: Deployment
metadata:
  name: unguard-user-simulator
  labels:
    app.kubernetes.io/name: user-simulator
    app.kubernetes.io/part-of: unguard
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: user-simulator
      app.kubernetes.io/part-of: unguard
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: user-simulator
        app.kubernetes.io/part-of: unguard
    spec:
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      containers:
        - name: main
          image: unguard-user-simulator
          env:
            - name: FRONTEND_ADDR
              value: "unguard-frontend:80/ui"
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
      initContainers:
        - name: wait-for-frontend
          image: curlimages/curl
          command: ["/bin/sh", "-c"]
          # CASP-8983 replace this endpoint with a proper health check endpoint
          args: [ 'while [ $(curl -ksw "%{http_code}" "http://unguard-frontend:80/ui/img/logo.svg" -o /dev/null) -ne 200 ]; do sleep 5; echo "health check failed . Waiting for the service..."; done' ]
