apiVersion: v1
kind: Service
metadata:
  name: vogelgrippe-user-auth-service
spec:
  ports:
    - targetPort: 9091
      port: 80
  type: ClusterIP
  selector:
    app: vogelgrippe-user-auth-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vogelgrippe-user-auth-service
spec:
  selector:
    matchLabels:
      app: vogelgrippe-user-auth-service
  template:
    metadata:
      labels:
        app: vogelgrippe-user-auth-service
    spec:
      containers:
        - name: user-auth-service
          image: vogelgrippe-user-auth-service
          ports:
            - containerPort: 9091
          env:
            - name: SERVER_PORT
              value: "9091"
            - name: JAEGER_AGENT_HOST
              value: "jaeger-agent" # change depending on your jaeger deployment
            - name: JAEGER_ENDPOINT
              value: "http://jaeger-collector:14268/api/traces"
            - name: JAEGER_SAMPLER_TYPE
              value: "const"
            - name: JAEGER_SAMPLER_PARAM
              value: "1"
            - name: REDIS_SERVICE_ADDRESS
              value: "vogelgrippe-redis"
            - name: MARIADB_SERVICE
              value: "mariadb-release"
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-release
                  key: mariadb-root-password